# Generated by Django 3.0.8 on 2020-07-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='d_o_b',
            field=models.DateTimeField(null=True, verbose_name='Date of birth'),
        ),
    ]
