# Generated by Django 3.0.8 on 2020-07-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0002_auto_20200720_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
