# Generated by Django 3.0.8 on 2020-07-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0002_profile_d_o_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='instapost',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
