# Generated by Django 3.0.8 on 2020-07-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0002_auto_20200730_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instapost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='instaclone.Profile'),
        ),
    ]
