# Generated by Django 3.0.8 on 2020-07-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0003_auto_20200720_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='instaclone.User'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='instaclone.User'),
        ),
    ]
