# Generated by Django 3.0.8 on 2020-07-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0003_instapost_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='/emptyprofilepic', upload_to='images/'),
        ),
    ]
