# Generated by Django 3.0.8 on 2020-07-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0003_auto_20200730_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instapost',
            name='caption',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='instapost',
            name='picture',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='instapost',
            name='post_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instapost',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Date Published'),
        ),
    ]
