# Generated by Django 3.0.8 on 2020-07-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0004_auto_20200726_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='/images/emptyprofilepic', upload_to='images/'),
        ),
    ]
