# Generated by Django 3.0.8 on 2020-07-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0005_auto_20200726_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='/emptyprofilepic', upload_to='images/'),
        ),
    ]
